### ISSUE TITLE
Plugin version 2.0.0-alpha1 compatibility with Kibana version 6.2.3 

### ISSUE THREAD

**Issue by thomasbinny1989** [novomatic-tech/keycloak-kibana#16]
Currently we see that 2.0.0-alpha1 is only compatible with a specific version
This version is compatible with Kibana 6.6.1

Though we tried installing the plugin we get an error as below.
./kibana-plugin install file:/Users/dhruva/Downloads/keycloak-kibana-2.0.0-alpha2/build/keycloak-kibana-2.0.0.zip
Attempting to transfer from file:/Users/dhruva/Downloads/keycloak-kibana-2.0.0-alpha2/build/keycloak-kibana-2.0.0.zip
Transferring 2452998 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error ""keycloak.serverUrl", "keycloak.realm", "keycloak.clientId", "keycloak.clientSecret", and "keycloak.session.cookieOptions.password" settings were not applied. Check for spelling errors and ensure that expected plugins are installed and enabled."

**Comment by tomnocon** [comment]
Hello @thomasbinny1989, as it is written in logs, you have to specify these settings in the ``kibana.yml`` file before plugin installation. Example:
```yaml
keycloak.serverUrl: http://localhost:8080/auth
keycloak.realm: kibana
keycloak.clientId: kibana
keycloak.clientSecret: y8gSCns8hPTkQr6Zqwu2hPw6ScQDZNZz
keycloak.session.cookieOptions.password: JWFn3Er]PqNZ7n{H$L9aa}Eeg#J`9?zb-/jyt?;#px>?@xaYrx_"P>Y%k[~7VGWV
```
We don't support all versions of kibana because the API changes significantly. You can try to build this plugin for yourself for a different version, but there is a high risk that some features may not work.
