### ISSUE TITLE
idp_entity_id elasticsearch with keycloak doesn't redirect to sso.keycloak

### ISSUE THREAD

**Issue by slashlinux** [novomatic-tech/keycloak-kibana#61]
Hi,

I've configured my elasticsearch with xpack ssl/tls in order to login on Kibana via Keycloak ssl but, when I run the kibana:5601 in my browser doesn't redirect me to the keyloack in order to enter my credentials and login to kibana.

**Here is my config for elasticsearch.yml**

```
xpack.security.enabled: true

xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: certs/elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: certs/elastic-certificates.p12

xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.keystore.path: certs/elastic-certificates.p12
xpack.security.http.ssl.truststore.path: certs/elastic-certificates.p12
xpack.security.authc.token.enabled: true
xpack.security.http.ssl.client_authentication: optional
#xpack.security.authc.realms.pki1.type: pki


xpack.security.authc.realms:
  saml.saml1:
    order: 2
    idp.metadata.path: saml-elasticsearch-metadata.xml
    idp.entity_id: "http://192.168.100.101:8080/auth/realms/grafana"
    sp.entity_id:  "http://192.168.100.101:5601/"
    sp.acs: "http://192.168.100.101:5601/api/security/v1/saml"
    sp.logout: "http://192.168.100.101:5601/logout"
    attributes.principal: "username"
    attributes.groups: "Role"
    nameid_format : "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
    force_authn: true
```

**My kibana,yml config:**

```
xpack.security.enabled: true
elasticsearch.username: "kibana"
elasticsearch.password: "kibana"
elasticsearch.ssl.certificateAuthorities: config/certs/client-ca.cer
elasticsearch.ssl.verificationMode: certificate
```

Can you please help me what I'm missing ?

![elastic_login](https://user-images.githubusercontent.com/32353453/140942779-ff7b51e8-4e0f-47d0-9824-ac5ded4b95f2.PNG)
